Repository hanna-eismant/doky, pull requests merged in 2022-12, with the labels that each got.

#19 Build Docker image
  docker-deployment/doky-server/Dockerfile
  docker-deployment/doky-server/README.md
  docker-deployment/doky-server/dev.yml
Labels: env tech

#20 Guide to Run Client
  client/README.md
  client/package.json
Labels: documentation

#28 #27: Refactor Security configuration
  .gitignore
  server/src/integration/java/org/hkurh/doky/AbstractIntegrationTest.java
  server/src/integration/java/org/hkurh/doky/SecurityIntegrationTest.java
  server/src/integration/java/org/hkurh/doky/controllers/DocumentControllerIntegrationTest.java
  server/src/integration/java/org/hkurh/doky/controllers/UserControllerIntegrationTest.java
  server/src/main/java/org/hkurh/doky/controllers/AuthorizationUserController.java
  server/src/main/java/org/hkurh/doky/controllers/DocumentController.java
  server/src/main/java/org/hkurh/doky/controllers/DokyControllerAdvice.java
  server/src/main/java/org/hkurh/doky/controllers/UserController.java
  server/src/main/java/org/hkurh/doky/controllers/data/DocumentRequest.java
  server/src/main/java/org/hkurh/doky/controllers/data/ErrorResponse.java
  server/src/main/java/org/hkurh/doky/controllers/data/UserRegistrationRequest.java
  server/src/main/java/org/hkurh/doky/security/DokyAuthority.java
  server/src/main/java/org/hkurh/doky/security/DokyUserDetails.java
  server/src/main/java/org/hkurh/doky/security/WebSecurityConfig.java
Labels: BE

#29 chore: make filename case consistent
  client/src/pages/Home/Home.jsx
Labels: bug, FE

#30 Rollup Livereload
  client/package-lock.json
  client/package.json
  client/rollup.config.js
Labels: FE

#34 chore: update server readme
  docker-deployment/doky-server/README.md
Labels: documentation
