Repository hanna-eismant/doky, pull requests merged in 2022-08, with the labels that each got.

#9 Routing
  client/package-lock.json
  client/package.json
  client/rollup.config.js
  client/src/App.jsx
  client/src/pages/Home/home.jsx
  client/src/pages/Home/index.js
  client/src/pages/Login/Login.jsx
  client/static/index.html
  client/static/styles.css
Labels: enhancement

#16 Migrate from maven to gradle
  .gitignore
  server/.mvn/wrapper/MavenWrapperDownloader.java
  server/.mvn/wrapper/maven-wrapper.jar
  server/.mvn/wrapper/maven-wrapper.properties
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/mvnw
  server/mvnw.cmd
  server/pom.xml
  server/settings.gradle
  server/src/integration/java/org/hkurh/doky/controllers/UserControllerIT.java
  server/src/integration/resources/META-INF/additional-spring-configuration-metadata.json
  server/src/integration/resources/application-local.properties
  server/src/integration/resources/application-test.properties
  server/src/integration/resources/application.properties
  server/src/integration/resources/sql/LoginControllerIntegrationTest/cleanup.sql
  server/src/integration/resources/sql/LoginControllerIntegrationTest/setup.sql
  server/src/main/resources/application-local.properties
  server/src/main/resources/application.properties
  server/src/test/java/org/hkurh/doky/facades/UserFacadeImplTest.java
Labels: enhancement

#15 Create rest endpoint to upload file
  server/build.gradle
  server/src/integration/java/org/hkurh/doky/controllers/AbstractIntegrationTest.java
  server/src/integration/java/org/hkurh/doky/controllers/DocumentControllerIntegrationTest.java
  server/src/integration/java/org/hkurh/doky/controllers/UserControllerIntegrationTest.java
  server/src/integration/resources/application-test.properties
  server/src/integration/resources/sql/DocumentControllerIntegrationTest/setup.sql
  server/src/integration/resources/sql/LoginControllerIntegrationTest/cleanup.sql
  server/src/integration/resources/sql/LoginControllerIntegrationTest/setup.sql
  server/src/integration/resources/sql/cleanup_base_test_data.sql
  server/src/integration/resources/sql/create_base_test_data.sql
  server/src/main/java/org/hkurh/doky/controllers/DocumentController.java
  server/src/main/java/org/hkurh/doky/controllers/DocumentRequest.java
  server/src/main/java/org/hkurh/doky/controllers/UserController.java
  server/src/main/java/org/hkurh/doky/dto/DocumentDto.java
  server/src/main/java/org/hkurh/doky/entities/DocumentEntity.java
  server/src/main/java/org/hkurh/doky/facades/DocumentFacade.java
  server/src/main/java/org/hkurh/doky/facades/MapperFactory.java
  server/src/main/java/org/hkurh/doky/facades/impl/DocumentFacadeImpl.java
  server/src/main/java/org/hkurh/doky/facades/impl/UserFacadeImpl.java
  server/src/main/java/org/hkurh/doky/repositories/DocumentEntityRepository.java
  server/src/main/java/org/hkurh/doky/services/DocumentService.java
  server/src/main/java/org/hkurh/doky/services/FileStorageService.java
  server/src/main/java/org/hkurh/doky/services/impl/DocumentServiceImpl.java
  server/src/main/java/org/hkurh/doky/services/impl/FileStorageServiceImpl.java
  server/src/main/java/org/hkurh/doky/services/impl/UserServiceImpl.java
  server/src/main/resources/db/migration/V5__add_document_creator.sql
  server/src/main/resources/db/migration/V6__remove_code_field_from_document.sql
  server/src/main/resources/db/migration/V7__add_file_path_to_document.sql
  server/src/test/java/org/hkurh/doky/controllers/UserControllerTest.java
  server/src/test/java/org/hkurh/doky/facades/UserFacadeImplTest.java
Labels: be tech

#17 Create Docker image and container for develop
  docker-deployment/doky-server/Dockerfile
  docker-deployment/doky-server/README.md
  docker-deployment/doky-server/dev.yml
  server/Dockerfile
  server/Doky-OpenAPI.yaml
  server/doky-servises.yml
Labels: env tech
